# Generated by Django 4.1.3 on 2022-12-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionDetail',
            fields=[
                ('exhibition_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('camera', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.CharField(blank=True, max_length=2000, null=True)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('keyword', models.CharField(blank=True, max_length=10, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.admin_account')),
            ],
            options={
                'db_table': 'exhibition_detail',
                'managed': True,
            },
        ),
    ]
