# Generated by Django 4.1.3 on 2022-12-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=25)),
                ('keyword', models.CharField(max_length=25)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Admin_account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=25, unique=True)),
                ('is_staff', models.BooleanField(default='True')),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=25)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Admin_account',
            },
        ),
    ]
